/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'HID.Release+B-U585I-IOT02A' 
 * Target:  'Release+B-U585I-IOT02A' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32u5xx.h"

/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.8.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
        #define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
        #define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:USB Device@3.0.0 */
#define RTE_Drivers_USBD0               /* Driver USBD0 */
        #define RTE_Drivers_USBD1               /* Driver USBD1 */
/* Keil::CMSIS Driver:VIO:Board&B-U585I-IOT02A@1.2.0 */
#define RTE_VIO_BOARD
        #define RTE_VIO_B_U585I_IOT02A
/* Keil::Device:Startup@1.2.0 */
#define RTE_DEVICE_STARTUP_STM32U5XX    /* Device Startup for STM32U5 */
/* Keil::USB&MDK:CORE&Release@6.17.0 */
#define RTE_USB_Core                    /* USB Core */
          #define RTE_USB_Core_Release            /* USB Core Release Version */
/* Keil::USB&MDK:Device:HID@6.17.0 */
#define RTE_USB_Device_HID_0            /* USB Device HID instance 0 */

/* Keil::USB&MDK:Device@6.17.0 */
#define RTE_USB_Device_0                /* USB Device 0 */



#endif /* RTE_COMPONENTS_H */
